# Aula — NumPy: arrays, slicing, fancy indexing, copy e view


Nesta aula, vamos estudar os fundamentos de NumPy que preparam o terreno para computação científica e Ciência de Dados em Python.

O foco será entender:

- como arrays NumPy são criados;
- como inspecionar sua estrutura;
- como acessar partes dos dados;
- quando um recorte gera uma cópia ou uma view;
- como selecionar elementos usando índices avançados e máscaras booleanas.

A aula foi pensada para alunos que já programam em C. Por isso, as explicações fazem comparações frequentes com vetores, matrizes, ponteiros, alocação de memória e manipulação manual de dados.

# Tópico 1 — Criação de arrays NumPy

Neste tópico, vamos começar a trabalhar com `NumPy`, uma das bibliotecas mais importantes para Ciência de Dados em Python.

Comparação com C:

- uma `list` em Python se comporta como uma sequência de **referências para objetos**;
- um `np.ndarray` armazena dados homogêneos em uma estrutura muito mais próxima de um **vetor tipado e contíguo em memória**, semelhante ao que fazemos em C com arrays de `int`, `float` ou `double`;
- em C, o programador gerencia diretamente a memória com variáveis, ponteiros, `malloc` e `free`;
- em NumPy, o objeto `ndarray` encapsula esse bloco de memória e guarda metadados como tipo dos dados, dimensão e formato.

Antes de fazer operações matemáticas avançadas com arrays, precisamos saber criá-los corretamente.

Neste tópico, vamos usar principalmente:

```python
np.array()
np.arange()
np.zeros()
np.ones()
```

---

## Contexto dos exercícios

Estamos **ajudando o P.U. a organizar seus dados para uma futura análise de vendas.**

Nesta primeira etapa, ainda não vamos fazer análises complexas. O objetivo é apenas representar corretamente os dados usando arrays NumPy.

# Exercício 1 — Criando um array com os preços dos produtos

A cafeteria universitária vende alguns produtos durante o dia: café, pão de queijo, suco, sanduíche e bolo.

Atualmente, os preços estão anotados manualmente em uma tabela. Queremos representar esses preços usando um array NumPy.

Em C, poderíamos armazenar esses valores em um vetor de `double`. Em Python puro, poderíamos usar uma lista. Com NumPy, usamos um `ndarray` com tipo numérico homogêneo.

### Requisitos

- Importe a biblioteca NumPy.
- Crie um array chamado `precos` com os preços dos produtos.
- Use `dtype=np.float64`.
- Exiba:
  - o array completo;
  - o tipo dos dados armazenados;
  - a quantidade de dimensões;
  - o formato do array;
  - a quantidade total de elementos.

In [3]:
import numpy as np
import numpy.typing as npt

# Lista de preços dos produtos: 4.50, 6.00, 7.50, 12.00, 5.50
# precos: npt.NDArray[np.float64] = ...  # <- continue o código

precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)
print(f"Array de preços: {precos}")
print(f"Tipo do array de preços: {type(precos)}")
print(f"Tipo dos dados armazenados: {precos.dtype}")
print(f"Número de dimensões: {precos.ndim}")
print(f"Formato do array: {precos.shape}")
print(f"Quantidade total de elementos: {precos.size}")

Array de preços: [ 4.5  6.   7.5 12.   5.5]
Tipo do array de preços: <class 'numpy.ndarray'>
Tipo dos dados armazenados: float64
Número de dimensões: 1
Formato do array: (5,)
Quantidade total de elementos: 5


# Exercício 2 — Criando códigos sequenciais para os produtos

A cafeteria deseja atribuir códigos internos aos produtos do cardápio.

Os códigos devem começar em `100` e terminar em `104`, um para cada produto cadastrado.

Em C, poderíamos preencher um vetor usando um `for`. Em NumPy, podemos criar essa sequência diretamente com `np.arange()`.

### Requisitos

- Crie um array chamado `codigos_produtos`.
- Os códigos devem ir de `100` até `104`.
- Use `np.arange()`.
- Use `dtype=np.int64`.
- Exiba o array criado.
- Exiba o tipo dos dados e o formato do array.

In [4]:
import numpy as np
import numpy.typing as npt

# Códigos dos produtos: de 100 até 104
codigos_produtos: npt.NDArray[np.int64] = np.arange(100, 105, dtype=np.int64)

print(f"Códigos dos produtos: {codigos_produtos}")
print(f"Tipo dos dados armazenados: {codigos_produtos.dtype}")
print(f"Formato do array: {codigos_produtos.shape}")

Códigos dos produtos: [100 101 102 103 104]
Tipo dos dados armazenados: int64
Formato do array: (5,)


# Exercício 3 — Inicializando o estoque diário com zeros

No início do dia, a cafeteria ainda não registrou nenhuma venda.

Queremos criar um array para armazenar a quantidade vendida de cada produto. Como nenhuma venda aconteceu ainda, todos os valores devem começar em zero.

Em C, seria comum declarar um vetor e inicializar suas posições manualmente ou com algum laço. Em NumPy, podemos usar `np.zeros()`.

### Requisitos

- Crie um array chamado `quantidades_vendidas`.
- O array deve ter 5 posições, uma para cada produto.
- Todos os valores devem começar em `0`.
- Use `dtype=np.int64`.
- Depois, simule algumas vendas alterando manualmente as posições:
  - produto 0: 12 unidades;
  - produto 1: 8 unidades;
  - produto 2: 5 unidades;
  - produto 3: 3 unidades;
  - produto 4: 10 unidades.
- Exiba o array antes e depois das alterações.

In [10]:
import numpy as np
import numpy.typing as npt

quantidades_vendidas: npt.NDArray[np.int64] = np.zeros(5, dtype=np.int64)
print(f"Vendas no início do dia: {quantidades_vendidas}")

# Atualize as quantidades vendidas:
# produto 0: 12
quantidades_vendidas[0] = 12
# produto 1: 8
quantidades_vendidas[1] = 8
# produto 2: 5
quantidades_vendidas[2] = 5
# produto 3: 3
quantidades_vendidas[3] = 3

quantidades_vendidas[4] = 7

quantidades_vendidas[1] += 2



print(f"Quantidades vendidas após alguns registros: {quantidades_vendidas}")
print(f"Tipo dos dados armazenados: {quantidades_vendidas.dtype}")
print(f"Formato do array: {quantidades_vendidas.shape}")

Vendas no início do dia: [0 0 0 0 0]
Quantidades vendidas após alguns registros: [12 10  5  3  7]
Tipo dos dados armazenados: int64
Formato do array: (5,)


# Exercício 4 — Marcando produtos disponíveis com ones

A cafeteria também quer manter um controle simples de disponibilidade dos produtos.

Vamos usar o valor `1` para indicar que um produto está disponível e `0` para indicar que está indisponível.

No início do dia, todos os produtos estão disponíveis. Portanto, podemos criar um array preenchido com `1`.

Em NumPy, usamos `np.ones()` para criar rapidamente esse tipo de estrutura.

### Requisitos

- Crie um array chamado `produtos_disponiveis`.
- O array deve ter 5 posições.
- Todas as posições devem começar com o valor `1`.
- Use `dtype=np.int64`.
- Depois, altere a posição do sanduíche para `0`, simulando que ele acabou.
- Exiba o array antes e depois da alteração.

In [12]:
import numpy as np
import numpy.typing as npt

produtos_disponiveis: npt.NDArray[np.bool_] = np.ones(5, dtype=np.bool_)

print(f"Disponibilidade inicial dos produtos: {produtos_disponiveis}")

# Índice do sanduíche na ordem dos produtos: 3
indice_sanduiche: int = 3

# Marque o sanduíche como indisponível.

print(f"Disponibilidade após o sanduíche acabar: {produtos_disponiveis}")
print(f"Tipo dos dados armazenados: {produtos_disponiveis.dtype}")
print(f"Formato do array: {produtos_disponiveis.shape}")

Disponibilidade inicial dos produtos: [ True  True  True  True  True]
Disponibilidade após o sanduíche acabar: [ True  True  True  True  True]
Tipo dos dados armazenados: bool
Formato do array: (5,)


# Exercício 5 — Organizando os dados em uma matriz do cardápio

Agora que já criamos arrays separados para códigos, preços, quantidades vendidas e disponibilidade, vamos combinar essas informações em uma única estrutura tabular.

A ideia é montar uma matriz NumPy em que:

- cada linha representa um produto;
- cada coluna representa uma informação sobre o produto.

A matriz seguirá esta ordem de colunas:

```python
[código, preço, quantidade vendida, disponibilidade]
```

Esse formato lembra uma matriz em C, como `double dados[5][4]`. Porém, existe um detalhe importante: arrays NumPy comuns possuem dados homogêneos. Como uma das colunas possui valores `float64`, o NumPy converte a matriz final para um tipo numérico comum.

### Requisitos

- Crie um array `codigos_produtos` com os códigos de `100` a `104`.
- Crie um array `precos` com 5 preços.
- Crie um array `quantidades_vendidas` preenchido inicialmente com zeros.
- Crie um array `produtos_disponiveis` preenchido inicialmente com uns.
- Combine esses arrays em uma matriz chamada `dados_cardapio`.
- A matriz deve ter 5 linhas e 4 colunas.
- Exiba:
  - a matriz completa;
  - o formato da matriz;
  - o tipo dos dados armazenados na matriz.
- Exiba os dados linha por linha, associando cada linha ao nome do produto correspondente.

In [ ]:
import numpy as np
import numpy.typing as npt

nomes_produtos: list[str] = [
    "Café",
    "Pão de queijo",
    "Suco",
    "Sanduíche",
    "Bolo"
]

# Crie os arrays abaixo (já criados nos exercícios anteriores).
codigos_produtos: npt.NDArray[np.int64] = np.arange(100, 105, dtype=np.int64)

precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)
quantidades_vendidas: npt.NDArray[np.int64] = np.zeros(5, dtype=np.int64)
produtos_disponiveis: npt.NDArray[np.bool_] = np.ones(5, dtype=np.int64)

# Combine os arrays como colunas de uma matriz.
dados_cardapio = np.column_stack((codigos_produtos, precos, quantidades_vendidas, produtos_disponiveis))

print("=== Matriz do cardápio ===")
print(dados_cardapio)

print("\n=== Estrutura da matriz ===")
print(f"Formato da matriz: {dados_cardapio.shape}")
print(f"Tipo dos dados armazenados: {dados_cardapio.dtype}")


print("\n=== Dados por produto ===")

indice_linha: int
linha: npt.NDArray[np.float64]

for indice_linha, linha in enumerate(dados_cardapio):
    nome: str = nomes_produtos[indice_linha]
    codigo: int = linha[0]
    preco: float = linha[1]
    vendidos: int = linha[2]
    disponivel: bool = linha[3]

    print(
        f"{nome} "
        f"código={codigo}, "
        f"preço=R$ {preco:.2f}, "
        f"vendidos={vendidos}, "
        f"disponível={disponivel}"
    )

=== Matriz do cardápio ===
[[100.    4.5   0.    1. ]
 [101.    6.    0.    1. ]
 [102.    7.5   0.    1. ]
 [103.   12.    0.    1. ]
 [104.    5.5   0.    1. ]]

=== Estrutura da matriz ===
Formato da matriz: (5, 4)
Tipo dos dados armazenados: float64

=== Dados por produto ===
Café código=100.0, preço=R$ 4.50, vendidos=0.0, disponível=1.0
Pão de queijo código=101.0, preço=R$ 6.00, vendidos=0.0, disponível=1.0
Suco código=102.0, preço=R$ 7.50, vendidos=0.0, disponível=1.0
Sanduíche código=103.0, preço=R$ 12.00, vendidos=0.0, disponível=1.0
Bolo código=104.0, preço=R$ 5.50, vendidos=0.0, disponível=1.0


In [35]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2))
print("concatenate")
print(arr)

arr = np.concatenate((arr3, arr4), axis=1)
print("concatenate duplo")
print(arr)
arr = np.stack((arr1, arr2), axis=1)
print("stack")
print(arr)
arr = np.hstack((arr1, arr2))
print("hstack")
print(arr)
arr = np.vstack((arr1, arr2))
print("vstack")
print(arr)
arr = np.dstack((arr1, arr2))
print("dstack")
print(arr)

concatenate
[1 2 3 4 5 6]
concatenate duplo
[[1 2 5 6]
 [3 4 7 8]]
stack
[[1 4]
 [2 5]
 [3 6]]
hstack
[1 2 3 4 5 6]
vstack
[[1 2 3]
 [4 5 6]]
dstack
[[[1 4]
  [2 5]
  [3 6]]]


## Cheat Sheet — Tópico 1: Criação de arrays NumPy

```python
import numpy as np
```

Importa a biblioteca NumPy usando o apelido padrão `np`.

```python
import numpy.typing as npt
```

Importa recursos de tipagem do NumPy, usados para indicar que uma variável é um array NumPy.

```python
np.array([...], dtype=...)
```

Cria um array NumPy a partir de uma sequência de valores. O parâmetro `dtype` define o tipo dos dados armazenados.

```python
np.arange(inicio, fim, dtype=...)
```

Cria uma sequência numérica no intervalo `[inicio, fim[`, ou seja, inclui o início e exclui o fim.

```python
np.zeros(tamanho, dtype=...)
```

Cria um array preenchido com zeros.

```python
np.ones(tamanho, dtype=...)
```

Cria um array preenchido com uns.

```python
np.column_stack((array1, array2, array3))
```

Combina arrays unidimensionais como colunas de uma matriz 2D.

```python
array.dtype
```

Mostra o tipo dos dados armazenados no array.

```python
array.ndim
```

Mostra a quantidade de dimensões do array.

```python
array.shape
```

Mostra o formato do array.

```python
array.size
```

Mostra a quantidade total de elementos do array.

```python
array[indice]
```

Acessa ou altera um elemento específico do array.

```python
enumerate(sequencia)
```

Percorre uma sequência retornando, ao mesmo tempo, o índice e o valor de cada item.

```python
npt.NDArray[tipo]
```

Indica, no type hint, que uma variável armazena um array NumPy.

```python
npt.NDArray[np.float64]
```

Indica um array NumPy com valores do tipo `float64`, parecido com um vetor de `double` em C.

```python
npt.NDArray[np.int64]
```

Indica um array NumPy com valores inteiros de 64 bits.

```python
np.float64
```

Tipo numérico de ponto flutuante de 64 bits usado pelo NumPy.

```python
np.int64
```

Tipo inteiro de 64 bits usado pelo NumPy.

```python
list[str]
```

Type hint para indicar uma lista de strings.

```python
int(valor)
```

Converte um valor para inteiro.

```python
float(valor)
```

Converte um valor para ponto flutuante.


# Tópico 2 — Atributos estruturais dos arrays

Depois de criar arrays NumPy, precisamos entender como inspecionar sua estrutura.

Em C, ao declarar um vetor como `int valores[5]`, o tamanho e o tipo dos dados estão definidos no código. Em uma matriz como `double matriz[3][4]`, o programador precisa saber exatamente quantas linhas e colunas existem.

Em NumPy, essas informações ficam armazenadas como metadados do próprio objeto `ndarray`.

Neste tópico, vamos usar principalmente:

```python
array.dtype
array.ndim
array.shape
array.size
array.reshape()
```

---

## Contexto dos exercícios

Continuamos ajudando o **P.U. a organizar seus dados para uma futura análise de vendas**.

Agora, além de criar os arrays, vamos inspecionar sua estrutura e reorganizar alguns dados em formatos mais adequados.

# Exercício 1 — Inspecionando a estrutura de um array de preços

A cafeteria quer conferir se o array de preços foi criado corretamente.

Antes de usar esses dados em análises futuras, precisamos verificar o tipo dos dados, a quantidade de dimensões, o formato e o total de elementos.

Em C, essas informações normalmente são controladas pelo programador. Em NumPy, elas ficam disponíveis diretamente no objeto.

### Requisitos

- Crie um array chamado `precos`.
- Use `dtype=np.float64`.
- Exiba:
  - o array completo;
  - o `dtype`;
  - o `ndim`;
  - o `shape`;
  - o `size`.

In [41]:
import numpy as np
import numpy.typing as npt

# Lista de preços dos produtos: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

print(f"Preços: {precos}")
print(f"dtype: {precos.dtype}")
print(f"ndim: {precos.ndim}")
print(f"shape: {precos.shape}")
print(f"size: {precos.size}")

Preços: [ 4.5  6.   7.5 12.   5.5]
dtype: float64
ndim: 1
shape: (5,)
size: 5


# Exercício 2 — Criando uma matriz de vendas por dia

O P.U. registrou a quantidade vendida de três produtos durante quatro dias.

Queremos representar esses dados em uma matriz, onde:

- cada linha representa um dia;
- cada coluna representa um produto.

Esse formato é parecido com uma matriz em C, por exemplo `int vendas[4][3]`.

### Requisitos

- Crie uma matriz chamada `vendas_semana`.
- A matriz deve ter 4 linhas e 3 colunas.
- Use `dtype=np.int64`.
- Exiba a matriz completa.
- Exiba `ndim`, `shape` e `size`.

In [43]:
import numpy as np
import numpy.typing as npt

# Matriz de vendas:
# Dia 0: 12, 8, 5
# Dia 1: 10, 7, 6
# Dia 2: 15, 9, 8
# Dia 3: 9, 6, 4
dia0: npt.NDArray[np.int64] = np.array([12, 8, 5], dtype=np.int64)
dia1: npt.NDArray[np.int64] = np.array([10, 7, 6], dtype=np.int64)
dia2: npt.NDArray[np.int64] = np.array([15, 9, 8], dtype=np.int64)
dia3: npt.NDArray[np.int64] = np.array([10, 7, 6], dtype=np.int64)

vendas_semana: npt.NDArray[np.int64] = np.array([dia0, dia1, dia2, dia3])

print("Vendas da semana:")
print(vendas_semana)

print(f"\nndim: {vendas_semana.ndim}")
print(f"shape: {vendas_semana.shape}")
print(f"size: {vendas_semana.size}")

Vendas da semana:
[[12  8  5]
 [10  7  6]
 [15  9  8]
 [10  7  6]]

ndim: 2
shape: (4, 3)
size: 12


# Exercício 3 — Transformando uma sequência em matriz

O P.U. recebeu os dados de vendas em uma sequência única, como se fosse um vetor linear.

Porém, sabemos que esses dados representam 4 dias e 3 produtos. Portanto, queremos reorganizar esse vetor em uma matriz 4x3.

Em C, isso exigiria cuidado com a forma como os dados estão armazenados linearmente na memória. Em NumPy, podemos usar `reshape()` para mudar a interpretação dimensional dos dados.

### Requisitos

- Crie um array chamado `vendas_lineares` com 12 valores.
- Use `np.arange()` para gerar valores de `1` até `12`.
- Reorganize esse array em uma matriz chamada `vendas_matriz`.
- A matriz deve ter 4 linhas e 3 colunas.
- Exiba o array original e a matriz reorganizada.
- Exiba o `shape` de ambos.

In [47]:
import numpy as np
import numpy.typing as npt

vendas_lineares: npt.NDArray[np.int64] = np.arange(1, 13)

vendas_matriz: npt.NDArray[np.int64] = vendas_lineares.reshape((4, 3))

print(f"Vendas em formato linear: {vendas_lineares}")
print(f"shape do array linear: {vendas_lineares.shape}")

print("\nVendas em formato de matriz:")
print(vendas_matriz)
print(f"shape da matriz: {vendas_matriz.shape}")

Vendas em formato linear: [ 1  2  3  4  5  6  7  8  9 10 11 12]
shape do array linear: (12,)

Vendas em formato de matriz:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape da matriz: (4, 3)


# Exercício 4 — Interpretando dados por turno

O P.U. registrou vendas de dois turnos, manhã e tarde, para três produtos durante dois dias.

Os dados chegaram em formato linear, mas queremos reorganizá-los em uma estrutura com três dimensões:

- dimensão 0: dia;
- dimensão 1: turno;
- dimensão 2: produto.

Essa estrutura já começa a mostrar que arrays NumPy podem representar mais do que matrizes 2D.

### Requisitos

- Crie um array chamado `vendas_lineares` com 12 valores.
- Reorganize os dados em um array chamado `vendas_por_turno`.
- O formato final deve ser `(2, 2, 3)`.
- Exiba o array resultante.
- Exiba `ndim`, `shape` e `size`.

In [48]:
import numpy as np
import numpy.typing as npt

# Dados lineares:
# 12, 8, 5, 10, 6, 4, 14, 9, 7, 11, 8, 6
vendas_lineares: npt.NDArray[np.int64] = np.array([12, 8, 5, 10, 6, 4, 14, 9, 7, 11, 8, 6], dtype=np.int64)
print(f"Vendas lineares: {vendas_lineares}")
# Reorganize os dados no formato (2, 2, 3).
vendas_por_turno: npt.NDArray[np.int64] = vendas_lineares.reshape((2, 2, 3))

print("Vendas por dia, turno e produto:")
print(vendas_por_turno)

print(f"\nndim: {vendas_por_turno.ndim}")
print(f"shape: {vendas_por_turno.shape}")
print(f"size: {vendas_por_turno.size}")

Vendas lineares: [12  8  5 10  6  4 14  9  7 11  8  6]
Vendas por dia, turno e produto:
[[[12  8  5]
  [10  6  4]]

 [[14  9  7]
  [11  8  6]]]

ndim: 3
shape: (2, 2, 3)
size: 12


# Exercício 5 — Verificando se o reshape é compatível

O P.U. quer reorganizar 15 registros de vendas em uma matriz com 5 linhas e 3 colunas.

Antes de fazer isso, precisamos garantir que o número total de elementos é compatível com o novo formato.

Em C, tentar acessar posições fora de uma região válida de memória pode gerar comportamento indefinido. Em NumPy, se o `reshape()` for incompatível, o erro é detectado automaticamente.

### Requisitos

- Crie um array chamado `registros_vendas` com 15 valores.
- Verifique se `registros_vendas.size` é igual a `5 * 3`.
- Se for compatível, crie a matriz `vendas_organizadas`.
- Exiba a matriz final.
- Exiba uma mensagem indicando se a reorganização foi possível.

In [49]:
import numpy as np
import numpy.typing as npt

# Crie uma sequência de 1 até 15.
registros_vendas: npt.NDArray[np.int64] = np.arange(1, 16, dtype=np.int64)

linhas: int = 5
colunas: int = 3
tamanho_array: int = linhas * colunas

# Verifique se o reshape é compatível.
if registros_vendas.size == tamanho_array:
    vendas_organizadas: npt.NDArray[np.int64] = registros_vendas.reshape((linhas, colunas))

    print("Reorganização possível.")
    print(vendas_organizadas)
    print(f"shape final: {vendas_organizadas.shape}")
# else:
#     print("Reorganização incompatível.")
#     print(f"Quantidade de elementos: {registros_vendas.size}")
#     print(f"Total esperado: {tamanho_array}")

Reorganização possível.
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
shape final: (5, 3)


## Cheat Sheet — Tópico 2: Atributos estruturais dos arrays

```python
array.dtype
```

Mostra o tipo dos dados armazenados no array.

```python
array.ndim
```

Mostra quantas dimensões o array possui.

```python
array.shape
```

Mostra o formato do array.

Em um array 1D, retorna algo como:

```python
(5,)
```

Em uma matriz 2D, retorna algo como:

```python
(4, 3)
```

```python
array.size
```

Mostra a quantidade total de elementos do array.

```python
array.reshape(novo_formato)
```

Reorganiza os dados em outro formato, desde que o número total de elementos continue o mesmo.

```python
array.reshape(linhas, colunas)
```

Reorganiza um array em uma matriz 2D.

```python
array.reshape(dim1, dim2, dim3)
```

Reorganiza um array em uma estrutura com três dimensões.

```python
np.arange(inicio, fim, dtype=...)
```

Cria uma sequência numérica. Foi usado neste tópico para criar dados lineares antes do `reshape()`.

```python
if condicao:
    ...
else:
    ...
```

Executa blocos diferentes dependendo de uma condição.

```python
linhas * colunas
```

Multiplica dois valores. Neste tópico, foi usado para calcular a quantidade esperada de elementos antes do `reshape()`.

```python
npt.NDArray[np.int64]
```

Type hint usado para indicar arrays NumPy com inteiros de 64 bits.


# Tópico 3 — Indexação e slicing

Depois de criar e inspecionar arrays, precisamos acessar partes específicas dos dados.

Em C, acessamos posições de vetores e matrizes com índices, como:

```c
vetor[i]
matriz[i][j]
```

Em NumPy, a ideia é parecida, mas com uma sintaxe mais expressiva, especialmente para matrizes.

Neste tópico, vamos usar principalmente:

```python
array[indice]
matriz[linha, coluna]
array[inicio:fim]
array[inicio:fim:passo]
matriz[linhas, colunas]
```

---

## Contexto dos exercícios

O P.U. agora quer consultar partes específicas dos dados já organizados.

O foco será acessar produtos, dias e subconjuntos de vendas sem ainda fazer cálculos vetorizados avançados.

# Exercício 1 — Acessando preços por índice

O P.U. possui um array com os preços dos produtos na seguinte ordem:

```python
["Café", "Pão de queijo", "Suco", "Sanduíche", "Bolo"]
```

Queremos acessar preços individuais usando índices.

Assim como em C, a indexação começa em `0`.

### Requisitos

- Crie uma lista `nomes_produtos`.
- Crie um array `precos`.
- Acesse o preço do primeiro produto.
- Acesse o preço do último produto usando índice negativo.
- Exiba os resultados usando f-strings.

In [51]:
import numpy as np
import numpy.typing as npt

nomes_produtos: list[str] = [
    "Café",
    "Pão de queijo",
    "Suco",
    "Sanduíche",
    "Bolo"
]

precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Acesse o primeiro preço e o último preço.
primeiro_preco: float = precos[0]
ultimo_preco: float = precos[-1]

print(f"{nomes_produtos[0]}: R$ {primeiro_preco:.2f}")
print(f"{nomes_produtos[-1]}: R$ {ultimo_preco:.2f}")

Café: R$ 4.50
Bolo: R$ 5.50


# Exercício 2 — Acessando uma venda específica em uma matriz

O P.U. registrou as vendas de três produtos durante quatro dias.

A matriz segue a lógica:

- cada linha representa um dia;
- cada coluna representa um produto.

Queremos acessar a quantidade vendida do produto `1` no dia `2`.

Em NumPy, usamos `matriz[linha, coluna]`, uma forma mais direta do que `matriz[linha][coluna]`.

### Requisitos

- Crie uma matriz `vendas_semana`.
- Acesse a venda do dia de índice `2` e produto de índice `1`.
- Exiba o valor encontrado.
- Exiba também uma frase explicando o índice usado.

In [57]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [2, 3, 2], [4, 1, 3]], dtype=np.int64)

indice_dia: int = 2
indice_produto: int = 1

# Acesse a venda do dia 2 e produto 1.
quantidade: int = vendas_semana[indice_dia, indice_produto]

print(f"Venda no dia de índice {indice_dia}, produto de índice {indice_produto}: {quantidade}")

Venda no dia de índice 2, produto de índice 1: 3


# Exercício 3 — Selecionando parte dos preços com slicing

O P.U. quer visualizar apenas os preços dos três produtos centrais do cardápio.

Para isso, podemos usar slicing.

Em C, seria necessário controlar manualmente os índices inicial e final em um laço. Em NumPy, usamos a sintaxe `inicio:fim`.

### Requisitos

- Crie um array `precos`.
- Selecione os elementos das posições `1`, `2` e `3`.
- Armazene o resultado em `precos_centrais`.
- Exiba o array original e o recorte obtido.
- Exiba o `shape` do recorte.

In [60]:
import numpy as np
import numpy.typing as npt

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Selecione os elementos das posições 1, 2 e 3.
precos_centrais: npt.NDArray[np.float64] = precos[1:4]

print(f"Preços originais: {precos}")
print(f"Preços centrais: {precos_centrais}")
print(f"shape do recorte: {precos_centrais.shape}")

Preços originais: [ 4.5  6.   7.5 12.   5.5]
Preços centrais: [ 6.   7.5 12. ]
shape do recorte: (3,)


# Exercício 4 — Selecionando linhas de uma matriz

O P.U. quer visualizar apenas os dados dos dois primeiros dias de vendas.

Como cada linha da matriz representa um dia, podemos usar slicing nas linhas.

### Requisitos

- Crie a matriz `vendas_semana`.
- Selecione apenas as duas primeiras linhas.
- Armazene o resultado em `primeiros_dias`.
- Exiba a matriz original.
- Exiba o recorte obtido.
- Exiba o `shape` do recorte.

In [63]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [1, 3, 2], [4, 2, 5]], dtype=np.int64)

# Selecione apenas as duas primeiras linhas.
primeiros_dias: npt.NDArray[np.int64] = vendas_semana[:2]

print("Matriz original:")
print(vendas_semana)

print("\nDois primeiros dias:")
print(primeiros_dias)

print(f"\nshape do recorte: {primeiros_dias.shape}")
print(f"\nndim do recorte: {primeiros_dias.ndim}")

Matriz original:
[[2 3 2]
 [4 1 3]
 [1 3 2]
 [4 2 5]]

Dois primeiros dias:
[[2 3 2]
 [4 1 3]]

shape do recorte: (2, 3)

ndim do recorte: 2


# Exercício 5 — Selecionando uma coluna da matriz

O P.U. quer visualizar as vendas de apenas um produto ao longo dos dias.

Como cada coluna representa um produto, podemos selecionar uma coluna específica da matriz.

Em NumPy, `:` significa “todas as linhas”.

### Requisitos

- Crie a matriz `vendas_semana`.
- Selecione todas as vendas do produto de índice `2`.
- Armazene o resultado em `vendas_produto`.
- Exiba o array resultante.
- Exiba o `shape` do resultado.

In [70]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [1, 3, 2], [4, 2, 5]], dtype=np.int64)

indice_produto: int = 2

# Selecione todas as vendas do produto de índice 2.
vendas_produto: npt.NDArray[np.int64] = vendas_semana[:, 2]

print(f"Vendas do produto de índice {indice_produto}: {vendas_produto}")
print(f"shape do resultado: {vendas_produto.shape}")

Vendas do produto de índice 2: [2 3 2 5]
shape do resultado: (4,)


## Cheat Sheet — Tópico 3: Indexação e slicing

```python
array[indice]
```

Acessa um elemento em um array 1D.

```python
array[-1]
```

Acessa o último elemento do array.

```python
matriz[linha, coluna]
```

Acessa um elemento específico de uma matriz NumPy.

```python
array[inicio:fim]
```

Seleciona elementos do índice `inicio` até antes do índice `fim`.

```python
array[inicio:fim:passo]
```

Seleciona elementos usando início, fim e passo.

```python
matriz[inicio:fim, :]
```

Seleciona um intervalo de linhas e todas as colunas.

```python
matriz[:, coluna]
```

Seleciona todas as linhas de uma coluna específica.

```python
matriz[linha, :]
```

Seleciona todas as colunas de uma linha específica.

```python
:
```

Representa “todos os elementos” naquela dimensão.

```python
float(array[indice])
```

Converte um valor extraído do array para `float` do Python.

```python
int(matriz[linha, coluna])
```

Converte um valor extraído da matriz para `int` do Python.

```python
list[str]
```

Type hint para indicar uma lista de strings.

```python
npt.NDArray[np.float64]
```

Type hint para indicar um array NumPy com valores de ponto flutuante de 64 bits.

```python
npt.NDArray[np.int64]
```

Type hint para indicar um array NumPy com valores inteiros de 64 bits.


# Tópico 4 — Copy e view

Em NumPy, nem todo recorte cria uma cópia independente dos dados.

Quando usamos slicing, muitas vezes o resultado é uma **view**, ou seja, uma nova forma de enxergar o mesmo bloco de memória.

Isso é muito importante para quem vem de C.

Em C, quando passamos um ponteiro para uma função ou acessamos uma parte de um vetor por deslocamento de endereço, podemos alterar os dados originais sem criar uma cópia. Em NumPy, uma view tem uma ideia parecida: ela aponta para os mesmos dados internos do array original, embora o acesso seja mediado pelo objeto `ndarray`.

Neste tópico, vamos usar principalmente:

```python
array[inicio:fim]
array.copy()
array.base
np.shares_memory()
```

---

## Contexto dos exercícios

O P.U. agora precisa tomar cuidado ao criar recortes dos dados de vendas.

Em algumas situações, queremos alterar diretamente os dados originais. Em outras, queremos trabalhar em uma cópia para evitar mudanças indesejadas.

# Exercício 1 — Alterando uma fatia e observando o array original

O P.U. quer corrigir temporariamente os preços dos produtos centrais.

Vamos criar uma fatia do array de preços e alterar um valor dessa fatia.

O objetivo é observar que, quando a fatia é uma view, a alteração também aparece no array original.

### Requisitos

- Crie um array `precos`.
- Crie uma fatia chamada `precos_centrais` com os elementos das posições `1` até `3`.
- Altere a primeira posição da fatia para `99.90`.
- Exiba a fatia.
- Exiba o array original.
- Observe se o array original também foi alterado.

In [72]:
import numpy as np
import numpy.typing as npt

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Crie uma fatia com os elementos das posições 1 até 3.
precos_centrais: npt.NDArray[np.float64] = precos[1:4]

# Altere a primeira posição da fatia para 99.90.
precos_centrais[0] = 1

print(f"Fatia alterada: {precos_centrais}")
print(f"Array original: {precos}")

Fatia alterada: [ 1.   7.5 12. ]
Array original: [ 4.5  1.   7.5 12.   5.5]


# Exercício 2 — Criando uma cópia segura com `.copy()`

Agora o P.U. quer testar uma alteração de preço sem modificar os dados originais.

Para isso, devemos criar uma cópia explícita usando `.copy()`.

Em C, seria como alocar outro vetor e copiar os valores manualmente. Em NumPy, `.copy()` cria um novo bloco de dados independente.

### Requisitos

- Crie um array `precos`.
- Crie uma cópia chamada `precos_teste` usando `.copy()`.
- Altere o primeiro valor da cópia para `99.90`.
- Exiba a cópia.
- Exiba o array original.
- Verifique que o array original não foi alterado.

In [75]:
import numpy as np
import numpy.typing as npt

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Crie uma cópia independente do array.
precos_teste: npt.NDArray[np.float64] = precos.copy()

# Altere o primeiro valor da cópia para 99.90.
precos_teste[0] = 1

print(f"Cópia alterada: {precos_teste}")
print(f"Array original: {precos}")

Cópia alterada: [ 1.   6.   7.5 12.   5.5]
Array original: [ 4.5  6.   7.5 12.   5.5]


# Exercício 3 — Verificando compartilhamento de memória

O P.U. quer confirmar se uma fatia compartilha memória com o array original.

Para isso, podemos usar `np.shares_memory()`.

Esse comando é útil para entender se estamos lidando com uma view ou com uma cópia.

### Requisitos

- Crie um array `precos`.
- Crie uma fatia com slicing.
- Crie uma cópia com `.copy()`.
- Use `np.shares_memory()` para verificar:
  - se a fatia compartilha memória com o original;
  - se a cópia compartilha memória com o original.
- Exiba os resultados.

In [77]:
import numpy as np
import numpy.typing as npt

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Crie uma fatia com slicing.
precos_fatia: npt.NDArray[np.float64] = precos[1:3]

# Crie uma cópia da mesma fatia.
precos_copia: npt.NDArray[np.float64] = precos_fatia.copy()

# Verifique o compartilhamento de memória.
fatia_compartilha_memoria: bool = np.shares_memory(precos_fatia, precos)
copia_compartilha_memoria: bool = np.shares_memory(precos_copia, precos)

print(f"A fatia compartilha memória com o original? {fatia_compartilha_memoria}")
print(f"A cópia compartilha memória com o original? {copia_compartilha_memoria}")

A fatia compartilha memória com o original? True
A cópia compartilha memória com o original? False


# Exercício 4 — Corrigindo vendas em uma view de matriz

O P.U. percebeu que os dados dos dois primeiros dias foram digitados com erro.

Vamos selecionar as duas primeiras linhas da matriz de vendas e alterar um valor dentro desse recorte.

Como o slicing de matriz também pode gerar view, a matriz original será alterada.

### Requisitos

- Crie a matriz `vendas_semana`.
- Crie uma view chamada `primeiros_dias`.
- Altere o primeiro valor de `primeiros_dias` para `99`.
- Exiba `primeiros_dias`.
- Exiba `vendas_semana`.
- Observe a alteração no array original.

In [78]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [1, 3, 2], [4, 2, 5]], dtype=np.int64)

# Crie uma view com as duas primeiras linhas.
primeiros_dias: npt.NDArray[np.int64] = vendas_semana[:2]

# Altere o primeiro valor da view para 99.
primeiros_dias[0, 0] = 99

print("Recorte dos primeiros dias:")
print(primeiros_dias)

print("\nMatriz original após alteração:")
print(vendas_semana)

Recorte dos primeiros dias:
[[99  3  2]
 [ 4  1  3]]

Matriz original após alteração:
[[99  3  2]
 [ 4  1  3]
 [ 1  3  2]
 [ 4  2  5]]


# Exercício 5 — Preservando a matriz original com cópia

Agora o P.U. quer testar correções nos dois primeiros dias sem alterar a matriz original.

Para isso, devemos criar uma cópia explícita do recorte.

### Requisitos

- Crie a matriz `vendas_semana`.
- Crie uma cópia chamada `primeiros_dias_teste`.
- Altere o primeiro valor da cópia para `99`.
- Exiba a cópia alterada.
- Exiba a matriz original.
- Use `np.shares_memory()` para confirmar que não há compartilhamento de memória.

In [80]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [1, 3, 2], [4, 2, 5]], dtype=np.int64)

# Crie uma cópia das duas primeiras linhas.
primeiros_dias_teste: npt.NDArray[np.int64] = vendas_semana.copy()[:2]

# Altere o primeiro valor da cópia para 99.
primeiros_dias_teste[0, 0] = 99

# Verifique se a cópia compartilha memória com a matriz original.
compartilha_memoria: bool = np.shares_memory(primeiros_dias_teste, vendas_semana)

print("Cópia alterada:")
print(primeiros_dias_teste)

print("\nMatriz original preservada:")
print(vendas_semana)

print(f"\nA cópia compartilha memória com a matriz original? {compartilha_memoria}")

Cópia alterada:
[[99  3  2]
 [ 4  1  3]]

Matriz original preservada:
[[2 3 2]
 [4 1 3]
 [1 3 2]
 [4 2 5]]

A cópia compartilha memória com a matriz original? False


## Cheat Sheet — Tópico 4: Copy e view

```python
array[inicio:fim]
```

Cria um recorte do array. Em muitos casos, esse recorte é uma view.

```python
matriz[linhas, colunas]
```

Cria um recorte de uma matriz. Também pode gerar uma view.

```python
array.copy()
```

Cria uma cópia independente dos dados.

```python
np.shares_memory(array1, array2)
```

Verifica se dois arrays compartilham a mesma região de memória.

```python
array.base
```

Pode indicar se um array foi criado a partir de outro array. É útil para investigação, mas `np.shares_memory()` costuma ser mais direto para fins didáticos.

```python
view[indice] = novo_valor
```

Altera o valor na view e pode alterar também o array original.

```python
copia[indice] = novo_valor
```

Altera somente a cópia, sem modificar o array original.

```python
bool
```

Type hint usado para indicar que uma variável guarda `True` ou `False`.

```python
npt.NDArray[np.float64]
```

Type hint para arrays NumPy com valores do tipo `float64`.

```python
npt.NDArray[np.int64]
```

Type hint para arrays NumPy com valores do tipo `int64`.


# Tópico 5 — Fancy indexing e máscaras booleanas

Além da indexação comum e do slicing, NumPy permite selecionar dados usando listas ou arrays de índices.

Isso é chamado de **fancy indexing**.

Também podemos selecionar dados usando condições, criando **máscaras booleanas**.

Esses dois recursos são muito importantes em Ciência de Dados, porque permitem filtrar dados sem escrever laços explícitos.

Em C, normalmente precisaríamos percorrer o vetor com `for`, testar condições com `if` e copiar manualmente os elementos desejados para outro vetor. Em NumPy, fazemos isso de forma mais direta.

Neste tópico, vamos usar principalmente:

```python
array[[indices]]
matriz[[linhas]]
array[mascara]
array[condicao]
```

---

## Contexto dos exercícios

O P.U. agora quer selecionar produtos e vendas específicas a partir de critérios mais flexíveis.

Vamos escolher produtos fora de ordem, filtrar preços e identificar registros de vendas com base em condições.

# Exercício 1 — Selecionando produtos fora de ordem

O P.U. quer montar uma pequena lista promocional com produtos específicos: bolo, café e suco.

Esses produtos não estão em posições consecutivas no array.

Com slicing, selecionamos intervalos contínuos. Com fancy indexing, podemos selecionar posições específicas, inclusive fora de ordem.

### Requisitos

- Crie uma lista `nomes_produtos`.
- Crie um array `precos`.
- Crie um array `indices_promocao` com os índices do bolo, café e suco.
- Use fancy indexing para selecionar os preços desses produtos.
- Exiba o nome e o preço de cada produto selecionado.

In [82]:
import numpy as np
import numpy.typing as npt

nomes_produtos: list[str] = [
    "Café",
    "Pão de queijo",
    "Suco",
    "Sanduíche",
    "Bolo"
]

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Índices dos produtos: bolo, café e suco
indices_promocao: npt.NDArray[np.int64] = [4, 0, 2]

# Selecione os preços usando fancy indexing.
precos_promocao: npt.NDArray[np.float64] = precos[indices_promocao]

print("Produtos selecionados para promoção:")

indice_original: np.int64
preco: np.float64

for indice_original, preco in zip(indices_promocao, precos_promocao):
    nome_produto: str = nomes_produtos[indice_original]

    print(f"{nome_produto}: R$ {preco:.2f}")

Produtos selecionados para promoção:
Bolo: R$ 5.50
Café: R$ 4.50
Suco: R$ 7.50


# Exercício 2 — Selecionando linhas específicas de uma matriz

O P.U. quer visualizar as vendas apenas dos dias de índice `0` e `2`.

Essas linhas não formam um intervalo contínuo com todos os dias entre elas. Por isso, usamos fancy indexing.

### Requisitos

- Crie a matriz `vendas_semana`.
- Crie um array `indices_dias`.
- Selecione as linhas de índice `0` e `2`.
- Armazene o resultado em `vendas_dias_escolhidos`.
- Exiba a matriz original.
- Exiba o recorte obtido.

In [84]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 2], [4, 1, 3], [1, 3, 2], [4, 2, 5]], dtype=np.int64)

# Índices dos dias escolhidos: 0 e 2
indices_dias: npt.NDArray[np.int64] = np.array([0, 2], dtype=np.int64)

# Selecione as linhas escolhidas.
vendas_dias_escolhidos: npt.NDArray[np.int64] = vendas_semana[indices_dias]

print("Matriz original:")
print(vendas_semana)

print("\nVendas dos dias escolhidos:")
print(vendas_dias_escolhidos)

Matriz original:
[[2 3 2]
 [4 1 3]
 [1 3 2]
 [4 2 5]]

Vendas dos dias escolhidos:
[[2 3 2]
 [1 3 2]]


# Exercício 3 — Filtrando produtos acima de certo preço

O P.U. quer listar apenas os produtos que custam pelo menos R$ 6,00.

Para isso, podemos criar uma máscara booleana. A comparação `precos >= 6.00` gera um array de `True` e `False`.

Depois, usamos essa máscara para selecionar apenas os valores desejados.

### Requisitos

- Crie uma lista `nomes_produtos`.
- Crie um array `precos`.
- Crie uma máscara chamada `mascara_precos_altos`.
- Selecione os preços maiores ou iguais a `6.00`.
- Exiba a máscara.
- Exiba os produtos filtrados com seus preços.

In [87]:
import numpy as np
import numpy.typing as npt

nomes_produtos: list[str] = [
    "Café",
    "Pão de queijo",
    "Suco",
    "Sanduíche",
    "Bolo"
]

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Crie a máscara para preços maiores ou iguais a 6.00.
mascara_precos_altos: npt.NDArray[np.bool_] = (precos > 6)

# Use a máscara para filtrar os preços.
precos_filtrados: npt.NDArray[np.float64] = precos[mascara_precos_altos]

print(f"Máscara booleana: {mascara_precos_altos}")
print("\nProdutos com preço maior ou igual a R$ 6,00:")

indice: int
preco: np.float64

for indice, preco in enumerate(precos):
    if mascara_precos_altos[indice]:
        nome_produto: str = nomes_produtos[indice]
        preco = precos[indice]
        print(f"{nome_produto}: R$ {preco:.2f}")
    pass

Máscara booleana: [False False  True  True False]

Produtos com preço maior ou igual a R$ 6,00:
Suco: R$ 7.50
Sanduíche: R$ 12.00


# Exercício 4 — Filtrando vendas baixas em uma matriz

O P.U. quer identificar valores de venda menores que `7`.

Ao aplicar uma condição diretamente sobre a matriz, o NumPy cria uma máscara booleana com o mesmo formato da matriz original.

Quando usamos essa máscara para filtrar a matriz, o resultado é um array 1D contendo apenas os valores que satisfazem a condição.

### Requisitos

- Crie a matriz `vendas_semana`.
- Crie uma máscara para valores menores que `7`.
- Use essa máscara para selecionar os valores.
- Exiba:
  - a matriz original;
  - a máscara booleana;
  - os valores filtrados.

In [89]:
import numpy as np
import numpy.typing as npt

# Crie a matriz de vendas da semana.
vendas_semana: npt.NDArray[np.int64] = np.array([[2, 3, 7], [4, 8, 3], [1, 3, 2], [10, 2, 5]], dtype=np.int64)

# Crie uma máscara para vendas menores que 7.
mascara_vendas_baixas: npt.NDArray[np.bool_] = (vendas_semana < 7)

# Use a máscara para filtrar as vendas.
vendas_baixas: npt.NDArray[np.int64] = vendas_semana[mascara_vendas_baixas]

print("Matriz de vendas:")
print(vendas_semana)

print("\nMáscara de vendas menores que 7:")
print(mascara_vendas_baixas)

print(f"\nValores filtrados: {vendas_baixas}")

Matriz de vendas:
[[ 2  3  7]
 [ 4  8  3]
 [ 1  3  2]
 [10  2  5]]

Máscara de vendas menores que 7:
[[ True  True False]
 [ True False  True]
 [ True  True  True]
 [False  True  True]]

Valores filtrados: [2 3 4 3 1 3 2 2 5]


# Exercício 5 — Comparando fancy indexing com slicing

O P.U. quer entender a diferença entre selecionar um intervalo contínuo e selecionar posições específicas.

Vamos comparar:

- slicing, que seleciona uma faixa contínua;
- fancy indexing, que seleciona índices escolhidos manualmente.

Esse exercício também mostra uma diferença importante de memória: slicing normalmente pode gerar view, enquanto fancy indexing geralmente gera uma cópia.

### Requisitos

- Crie um array `precos`.
- Crie um recorte com slicing usando `precos[1:4]`.
- Crie uma seleção com fancy indexing usando os índices `[1, 2, 3]`.
- Use `np.shares_memory()` para verificar se cada resultado compartilha memória com o array original.
- Exiba os dois resultados.
- Exiba as verificações de memória.

In [90]:
import numpy as np
import numpy.typing as npt

# Lista de preços: 4.50, 6.00, 7.50, 12.00, 5.50
precos: npt.NDArray[np.float64] = np.array([4.50, 6.00, 7.50, 12.00, 5.50], dtype=np.float64)

# Índices escolhidos: 1, 2 e 3
indices: npt.NDArray[np.int64] = np.array([1, 2, 3], dtype=np.int64)

# Selecione os preços usando slicing.
precos_slicing: npt.NDArray[np.float64] = precos[1:4]

# Selecione os preços usando fancy indexing.
precos_fancy: npt.NDArray[np.float64] = precos[indices]

# Verifique compartilhamento de memória.
slicing_compartilha_memoria: bool = np.shares_memory(precos, precos_slicing)
fancy_compartilha_memoria: bool = np.shares_memory(precos, precos_fancy)

print(f"Resultado com slicing: {precos_slicing}")
print(f"Resultado com fancy indexing: {precos_fancy}")

print(f"\nSlicing compartilha memória com o original? {slicing_compartilha_memoria}")
print(f"Fancy indexing compartilha memória com o original? {fancy_compartilha_memoria}")

Resultado com slicing: [ 6.   7.5 12. ]
Resultado com fancy indexing: [ 6.   7.5 12. ]

Slicing compartilha memória com o original? True
Fancy indexing compartilha memória com o original? False


## Cheat Sheet — Tópico 5: Fancy indexing e máscaras booleanas

```python
array[[indice1, indice2, indice3]]
```

Seleciona posições específicas de um array.

```python
array[indices]
```

Seleciona posições usando um array de índices.

```python
matriz[indices_linhas]
```

Seleciona linhas específicas de uma matriz.

```python
array[condicao]
```

Filtra valores de um array com base em uma condição.

```python
array >= valor
```

Gera uma máscara booleana indicando quais elementos são maiores ou iguais ao valor.

```python
array < valor
```

Gera uma máscara booleana indicando quais elementos são menores que o valor.

```python
array[mascara]
```

Seleciona apenas os elementos em que a máscara é `True`.

```python
np.bool_
```

Tipo booleano usado pelo NumPy em arrays de máscaras.

```python
zip(array1, array2)
```

Percorre duas sequências ao mesmo tempo.

```python
enumerate(sequencia)
```

Percorre uma sequência retornando índice e valor.

```python
np.shares_memory(array1, array2)
```

Verifica se dois arrays compartilham memória.

No contexto deste tópico:

- slicing geralmente pode compartilhar memória;
- fancy indexing geralmente cria uma cópia.

```python
npt.NDArray[np.bool_]
```

Type hint para arrays NumPy booleanos, usados como máscaras.

```python
np.float64
```

Tipo de valor numérico de ponto flutuante retornado por arrays NumPy com `dtype=np.float64`.

```python
np.int64
```

Tipo de valor inteiro retornado por arrays NumPy com `dtype=np.int64`.

```python
int(valor)
```

Converte um valor para inteiro. Foi usado para converter índices NumPy antes de acessar listas Python.

```python
if mascara[indice]:
    ...
```

Executa um bloco apenas quando a posição correspondente da máscara booleana é `True`.

```python
pass
```

Comando vazio em Python. Serve como marcador temporário para um bloco que ainda será preenchido.
